#!/usr/bin/env bash

language="en"
if [[ ! -z "${1}" ]]; then
    language="${1}"
fi

echo -e "\n  • Preview in AppCenter using locale ${language}"

echo -e "\n  • Temporarily uncommenting icon in metadata so it displays in preview."
sed -i 's/<!-- <icon type="stock">com.github.{GITHUB.ORG}.{GITHUB.APP}<\/icon> -->/<icon type="stock">com.github.{GITHUB.ORG}.{GITHUB.APP}<\/icon>/' data/{GITHUB.APP}.appdata.xml.in

echo -e "\n  • Building and installing app and AppCenter metadata."

# Ensure an up-to-date build exists and is installed.
task/install

echo -e "\n  • Previewing in AppCenter. When done, exit AppCenter (do not press Ctrl+C here as we need to perform clean-up)."

# Preview in the elementary OS AppCenter using the requested (or default) locale.
LANGUAGE="${language}" io.elementary.appcenter --load-local build/com.github.{GITHUB.ORG}.{GITHUB.APP}.appdata.xml

echo -e "\n  • Re-commenting out icon in metadata so Flatpak doesn’t complain."

sed -i 's/<icon type="stock">com.github.{GITHUB.ORG}.{GITHUB.APP}<\/icon>/<!-- <icon type="stock">com.github.{GITHUB.ORG}.{GITHUB.APP}<\/icon> -->/' data/{GITHUB.APP}.appdata.xml.in

echo -e "\nDone!"
