#!/usr/bin/env bash

#
# Ensure GPG key exists
#

echo -e "\nPublishing.\n"

gpg_home_directory="${HOME}/.small-tech.org/watson/com.github.{GITHUB.ORG}.{GITHUB.APP}/gpg"

function gpg_key_id {
    echo "$(gpg2 --homedir=${gpg_home_directory} --list-keys --with-colons | grep 'fpr.*' | sed 's/fpr//g' | sed 's/://g')"
}

# Ensure GPG keys exist.
if [[ ! -d "${gpg_home_directory}/private-keys-v1.d" ]]; then
    # Update status.
    echo -e "  • GPG key does not exist; creating.\n"

    # Ensure GPG home directory (homedir) exists.
    mkdir -p "${gpg_home_directory}"

    # Set the correct permissions for the home directory.
    chmod 700 "${gpg_home_directory}"

    # Create GPG key.
    gpg2 --batch --homedir gpg --passphrase '' --quick-gen-key {COPYRIGHT.EMAIL} - - never

    # Get the public key, in base64, with newlines stripped
    # to include in our .flatpakref file.
    gpg_public_key_base64="$(gpg2 --homedir=${gpg_home_directory} --export $(gpg_key_id) | base64 | tr -d '\n')"

    # Update the .flatpakref file with the GPG public key in base64.
    sed --in-place "s/{GPGKey}/${gpg_public_key_base64}/" docs/com.github.{GITHUB.ORG}.{GITHUB.APP}.flatpakref
fi

echo -e "  • Creating Flatpak package.\n"

task/package

echo -e "\n  • Exporting repository.\n"

flatpak build-export --gpg-sign="$(gpg_key_id)" --gpg-homedir="${gpg_home_directory}" docs/repo build stable

echo -e "\n  • Creating static deltas.\n"

flatpak build-update-repo docs/repo --gpg-sign="$(gpg_key_id)" --gpg-homedir="${gpg_home_directory}" --generate-static-deltas

echo -e "\n  • Done!\n"
echo -e "You can find the site and your latest repository in the docs/ directory.\n"
